### ISSUE TITLE
.dom and index not found issues

### ISSUE THREAD

**Issue by BauerKristof** [abishekshyamsunder/instagram-account-bot#1]
Hey there.
I have two main issues:
The first one at login.py the dom variables gave me errors, I fixed it by replacing them with driver
The second one which is the major one is when the page with birthdays loads, I guess it is waiting for the email with verification code for like 15-20 sec and after that I get the error code that: IndexError: list index out of range

The full process:
```python
DevTools listening on ws://127.0.0.1:55791/devtools/browser/1055b593-cfa3-4260-8a9c-4d4818c3ca78
Point(x=923, y=365)
Point(x=923, y=365)

DevTools listening on ws://127.0.0.1:55861/devtools/browser/0feb8035-7e83-4e70-a1ff-fd57d57c7a06
<span class="animace" id="email" style="font-size: 1.4em;">makani.nickai@outree.org</span>
Getting page source
In For loop
Traceback (most recent call last):
  File "c:/...../instagram-account-bot-master/login.py", line 110, in <module>
    main()
  File "c:/....../instagram-account-bot-master/login.py", line 99, in main
    x = x[0]
IndexError: list index out of range
```

**Comment by abishekshyamsunder** [comment]
Hey, Thanks for reaching out to me!
Sometimes this message gets raised when we try searching for the verification code, when it has not yet been received in the inbox. 
Please run your program without any changes (usually this works), or increase the time that the program sleeps before checking the inbox...
If this works, I will close the issue!

**Comment by abishekshyamsunder** [comment]
I am closing this issue. Please open a new issue of the problem persists!
Thanks for reaching out!
